name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد
        uses: actions/checkout@v4

      - name: ساخت APK با Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: stable

      - name: آپلود فایل APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
