name: Build APK

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev cmake libffi-dev libssl-dev build-essential \
            liblzma-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev \
            libreadline-dev libjpeg-dev libedit-dev libgdbm-dev \
            g++-multilib openjdk-17-jdk git zip unzip
            
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Build APK
        run: |
          # استفاده از yes | باعث می‌شود به تمام درخواست‌های تایید مجوز، به صورت خودکار پاسخ y داده شود
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
